
package edu.javacourse.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SayHelloServiceService", targetNamespace = "http://webservice.javacourse.edu/", wsdlLocation = "http://localhost:8080/sayHello/SayHelloService?wsdl")
public class SayHelloServiceService
    extends Service
{

    private final static URL SAYHELLOSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.javacourse.webservice.SayHelloServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.javacourse.webservice.SayHelloServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/sayHello/SayHelloService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/sayHello/SayHelloService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SAYHELLOSERVICESERVICE_WSDL_LOCATION = url;
    }

    public SayHelloServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SayHelloServiceService() {
        super(SAYHELLOSERVICESERVICE_WSDL_LOCATION, new QName("http://webservice.javacourse.edu/", "SayHelloServiceService"));
    }

    /**
     * 
     * @return
     *     returns SayHelloService
     */
    @WebEndpoint(name = "SayHelloServicePort")
    public SayHelloService getSayHelloServicePort() {
        return super.getPort(new QName("http://webservice.javacourse.edu/", "SayHelloServicePort"), SayHelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SayHelloService
     */
    @WebEndpoint(name = "SayHelloServicePort")
    public SayHelloService getSayHelloServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.javacourse.edu/", "SayHelloServicePort"), SayHelloService.class, features);
    }

}
