<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<definitions targetNamespace="http://test.gs.ru/" name="AsyncWebServiceService" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:tns="http://test.gs.ru/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://test.gs.ru/" schemaLocation="AsyncWebServiceService_schema1.xsd"/>
    </xsd:schema>
  </types>
  <message name="sayHelloSloooooowly">
    <part name="parameters" element="tns:sayHelloSloooooowly"/>
  </message>
  <message name="sayHelloSloooooowlyResponse">
    <part name="parameters" element="tns:sayHelloSloooooowlyResponse"/>
  </message>
  <portType name="AsyncWebService">
    <operation name="sayHelloSloooooowly">
      <input message="tns:sayHelloSloooooowly"/>
      <output message="tns:sayHelloSloooooowlyResponse"/>
    </operation>
  </portType>
  <binding name="AsyncWebServicePortBinding" type="tns:AsyncWebService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="sayHelloSloooooowly">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="AsyncWebServiceService">
    <port name="AsyncWebServicePort" binding="tns:AsyncWebServicePortBinding">
      <soap:address location="REPLACE_WITH_ACTUAL_URL"/>
    </port>
  </service>
</definitions>

